name: Firebase

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ready files
        uses: actions/checkout@v2
      
      - name: Deploy
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --only-hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
